VL-Launcher/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace VL_Launcher.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VL-Launcher/Pages/Index.cshtml.cs
using System;
using ElectronNET.API;
using ElectronNET.API.Entities;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VL_Launcher.Pages
{
    public class IndexModel : PageModel
    {

        private static bool Updated = false;

        public void OnGet()
        {
            if (!Updated) {
                Updated = true;
                // TODO: Implementation
            }
        }
    }
}

VL-Launcher/Pages/Launcher.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CmlLib.Core.Downloader;
using CmlLib.Core;
using System.IO;
using CmlLib.Core.Version;
using CmlLib.Core.Auth;
using Microsoft.AspNetCore.Http;
using System.Threading;

namespace VL_Launcher.Pages
{
    public class LauncherModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        [BindProperty]
        public int Memory { get; set; }

        [BindProperty]
        public string Version { get; set; }

        [BindProperty]
        public bool Fullscreen { get; set; }

        public void ChangeOption(string rootPath, string lang)
        {
            string[] properties;
            if (System.IO.File.Exists(rootPath + "/options.txt"))
            {
                properties = System.IO.File.ReadAllLines(rootPath + "/options.txt");
                for (int t = 0; t < properties.Length; t++)
                {
                    if (properties[t].Split(':')[0] == "gamma")
                    {
                        properties[t] = properties[t].Replace("1", "0").Replace("2", "0").Replace("3", "0").Replace("4", "0").Replace("5", "0").Replace("6", "0").Replace("7", "0").Replace("8", "0").Replace("9", "0");
                        continue;
                    }
                    if (properties[t].Split(':')[0] == "lang")
                    {
                        properties[t] = "lang:" + lang;
                        continue;
                    }
                }
            }
            else
            {
                properties = new string[]
                {
                    "lang:" + lang,
                    "lastServer:124.71.131.172",
                    "skipMultiplayerWarning:true",
                    "joinedFirstServer:true",
                    "gamma:0.0"
                };
            }
            System.IO.File.WriteAllLines(rootPath + "/options.txt", properties);
        }

        private static string LFileKind = string.Empty;
        private static string LFileName = string.Empty;
        private static string LProgressedFileCnt = "0";
        private static string LTotFileCnt = "?";
        private static string LProgressPercentage = "0";
        private static string LSuccess = "false";
        private static bool LStarted = false;

        public string Launch(string username, string password, int memory, string version, bool fullScreen)
        {
            var account = new MLogin().Authenticate(username, password);
            if (!account.IsSuccess)
                return account.Result.ToString() + '\n' + account.ErrorMessage;
            var session = account.Session;
            var mcp = new MinecraftPath(Path.Combine(Utility.GetWorkingDir(), ".minecraft"));
            ChangeOption(mcp.BasePath, Thread.CurrentThread.CurrentUICulture.Name.Replace('-', '_').ToLower());
            var launcher = new CMLauncher(mcp);
            launcher.FileChanged += (e) => {
                LFileKind = e.FileKind.ToString();
                LFileName = e.FileName;
                LProgressedFileCnt = e.ProgressedFileCount.ToString();
                LTotFileCnt = e.TotalFileCount.ToString();
            };
            launcher.ProgressChanged += (sender, e) => {
                LProgressPercentage = e.ProgressPercentage.ToString();
            };
            var launchOption = new MLaunchOption
            {
                MaximumRamMb = memory,
                Session = session,
                FullScreen = fullScreen,
                ServerIp = "124.71.131.172",
                ServerPort = 25565,
                JavaPath = Utility.GetJava(launcher),
                JVMArguments = new string[] {
                    "-javaagent:../nide8auth.jar=28f8f58a8a7f11e88feb525400b59b6a",
                    "-Dnide8auth.client=true"
                }
            };
            var process = launcher.CreateProcess(version, launchOption);
            Console.WriteLine("[Launch] FileName: " + process.StartInfo.FileName);
            Console.WriteLine("[Launch] Arguments: " + process.StartInfo.Arguments);
            Console.WriteLine("[Launch] WorkingDirectory: " + process.StartInfo.WorkingDirectory);
            process.Start();
            return string.Empty;
        }

        public async Task<IActionResult> OnPostLogin()
        {
            if (DLStarted == true)
            {
                HttpContext.Session.Set("DLQueryProgress", true);
                return RedirectToPage("/Launcher");
            }
            CookieOptions cookieOptions = new CookieOptions()
            {
                Expires = DateTime.Now.AddDays(7)
            };
            Response.Cookies.Append("Username", Username ?? string.Empty, cookieOptions);
            Response.Cookies.Append("Password", Password ?? string.Empty, cookieOptions);
            Response.Cookies.Append("Version", Version ?? string.Empty, cookieOptions);
            Response.Cookies.Append("Fullscreen", Fullscreen.ToString(), cookieOptions);
            HttpContext.Session.Set("LQueryProgress", true);
            if (LStarted == false) {
                LStarted = true;
                LFileKind = string.Empty;
                LFileName = string.Empty;
                LProgressedFileCnt = "0";
                LTotFileCnt = "?";
                LProgressPercentage = "0";
                LSuccess = "false";
                await Task.Run(() => {
                    try
                    {
                        string err = Launch(Username, Password, Memory, Version, Fullscreen);
                        if (err != string.Empty)
                        {
                            HttpContext.Session.Set("ErrorMsg", err);
                        }
                        else
                        {
                            HttpContext.Session.Set("SuccessMsg", Translation.Translate("launcher-success-login"));
                        }
                    }
                    catch (Exception e)
                    {
                        HttpContext.Session.Set("ErrorMsg", e.Message);
                    }
                    HttpContext.Session.Set("LQueryProgress", false);
                    LSuccess = "true";
                    LStarted = false;
                });
            }
            return RedirectToPage("/Launcher");
        }

        public IActionResult OnGetLoginStatus()
        {
            Dictionary<string, string> ans = new Dictionary<string, string>()
            {
                { "kind", LFileKind },
                { "name", LFileName },
                { "pgfc", LProgressedFileCnt },
                { "ttfc", LTotFileCnt },
                { "prog", LProgressPercentage },
                { "success", LSuccess }
            };
            return new JsonResult(ans);
        }

        public static MVersionCollection LoadVersions()
        {
            var mcp = new MinecraftPath(Path.Combine(Utility.GetWorkingDir(), ".minecraft"));
            var launcher = new CMLauncher(mcp);
            return launcher.GetAllVersions();
        }

        public IActionResult OnPostRegister()
        {
            Utility.OpenBrowser("https://login2.nide8.com:233/28f8f58a8a7f11e88feb525400b59b6a/register");
            return RedirectToPage("/Launcher");
        }

        private static string DLFileKind = string.Empty;
        private static string DLFileName = string.Empty;
        private static string DLProgressedFileCnt = "0";
        private static string DLTotFileCnt = "?";
        private static string DLProgressPercentage = "0";
        private static string DLSuccess = "false";
        private static bool DLStarted = false;

        public async Task<IActionResult> OnPostDownload()
        {
            if (LStarted == true)
            {
                HttpContext.Session.Set("LQueryProgress", true);
                return RedirectToPage("/Launcher");
            }
            HttpContext.Session.Set("DLQueryProgress", true);
            if (DLStarted == false) {
                DLStarted = true;
                DLFileKind = string.Empty;
                DLFileName = string.Empty;
                DLProgressedFileCnt = "0";
                DLTotFileCnt = "?";
                DLProgressPercentage = "0";
                DLSuccess = "false";
                var minecraft = new MinecraftPath(Path.Combine(Utility.GetWorkingDir(), ".minecraft"));
                var versionMetadatas = new MVersionLoader().GetVersionMetadatas(minecraft);
                var version = versionMetadatas.GetVersion("1.16.5");
                MDownloader downloader = new MDownloader(minecraft, version);
                downloader.ChangeFile += (e) => {
                    DLFileKind = e.FileKind.ToString();
                    DLFileName = e.FileName;
                    DLProgressedFileCnt = e.ProgressedFileCount.ToString();
                    DLTotFileCnt = e.TotalFileCount.ToString();
                };
                downloader.ChangeProgress += (sender, e) => {
                    DLProgressPercentage = e.ProgressPercentage.ToString();
                };
                await Task.Run(() => {
                    try
                    {
                        downloader.DownloadAll();
                        HttpContext.Session.Set("SuccessMsg", Translation.Translate("launcher-success-dl"));
                    } catch (Exception e)
                    {
                        HttpContext.Session.Set("ErrorMsg", e.Message);
                    }
                    HttpContext.Session.Set("DLQueryProgress", false);
                    DLSuccess = "true";
                    DLStarted = false;
                });
            }
            return RedirectToPage("/Launcher");
        }

        public IActionResult OnGetDownloadStatus()

VL-Launcher/Pages/About.cshtml
@page
@model LauncherModel
@{
    ViewData["Title"] = Translation.Translate("about");
}

<h1 class="display-4">@Translation.Translate("about")</h1>

<button type="button" class="btn btn-primary" onclick="window.history.back();">@Translation.Translate("back")</button>

<br /><br />

      <p>
          <b>VL-Minecraft</b> @System.Reflection.Assembly.GetExecutingAssembly().GetName().Version
          <br />
          @Translation.Translate("copyright") &copy; 2021 TURX
          <br />
          @Translation.Translate("oss")
      </p>

<h4>@Translation.Translate("credits")</h4>

Backend:

<ul>
    <li>.NET 5 &copy; .NET Foundation, Contributors [MIT License]</li>
    <li>BMCLAPI &copy; bangbang93 [Open API]</li>
    <li>BMCLAPI MCBBS Mirror &copy; bangbang93, MCBBS [Open API]</li>
    <li>CmlLib.Core &copy; 2020 권세인 (AlphaBs) [MIT License]</li>
    <li>ElectronNET.API &copy; 2017 Gregor Biswanger, Robert Mühsig [MIT License]</li>
    <li>ICSharpCode.SharpZipLib &copy; 2000-2018 SharpZipLib Contributors [MIT License]</li>
    <li>LZMA-SDK &copy; 2020 Mihir Mone [MIT License]</li>
    <li>Newtonsoft.Json &copy; 2007 James Newton-King [MIT License]</li>
</ul>

Frontend:

<ul>
    <li>Bootstrap &copy; 2011-2018 Twitter, Inc., The Bootstrap Authors [MIT License]</li>
    <li>jQuery &copy; OpenJS Foundation, Contributors [MIT License]</li>
    <li>jQuery Validation &copy; Jörn Zaefferer [MIT License]</li>
    <li>jQuery Validation Unobtrusive &copy; .NET Foundation [Apache License v2]</li>
</ul>

VL-Launcher/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = Translation.Translate("welcome");
}

<h1 class="display-4">
    @Translation.Translate("welcome")
    <small class="text-muted">@Translation.Translate("head")</small>
</h1>

<a class="btn btn-primary" asp-page="/Launcher">@Translation.Translate("launcher")</a>&emsp;<a class="btn btn-primary" asp-page="/About">@Translation.Translate("about")</a>

<br />
<br />

<div class="card">
    <div class="card-body">
        <h5 class="card-title">@Translation.Translate("welcome-intro-head")</h5>
        <p class="card-text">@Translation.Translate("welcome-intro-txt")</p>
    </div>
</div>

<br />

<div class="card">
    <div class="card-body">
        <h5 class="card-title">@Translation.Translate("welcome-auth-head")</h5>
        <p class="card-text">@Translation.Translate("welcome-auth-txt")</p>
    </div>
</div>

<br />

<div class="card">
    <div class="card-body">
        <h5 class="card-title">@Translation.Translate("welcome-unix-head")</h5>
        <p class="card-text">@Translation.Translate("welcome-unix-txt")</p>
    </div>
</div>

VL-Launcher/Pages/Launcher.cshtml
@page
@model LauncherModel
@{
    ViewData["Title"] = Translation.Translate("launcher");
}

<h1 class="display-4">@Translation.Translate("launcher")</h1>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/launcher.js" asp-append-version="true"></script>

@if (HttpContext.Session.Get<string>("SuccessMsg") != null)
{
    <div class="alert alert-success" role="alert">
        <strong>@Translation.Translate("success")</strong> @(HttpContext.Session.Get<string>("SuccessMsg"))
    </div>
    HttpContext.Session.Remove("SuccessMsg");
}

@if (HttpContext.Session.Get<string>("ErrorMsg") != null)
{
    <div class="alert alert-danger" role="alert">
        <strong>@Translation.Translate("error")</strong> @(HttpContext.Session.Get<string>("ErrorMsg"))
    </div>
    HttpContext.Session.Remove("ErrorMsg");
}

<p>@Translation.Translate("current-dir"): @Utility.GetWorkingDir()</p>

<div class="collapse" id="prog">
    <div class="card">
        <div class="card-body">
            <div class="progress">
                <div id="prog-whole" class="progress-bar progress-bar-striped progress-bar-animated active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
            </div>
            <br />
            <div class="progress">
                <div id="prog-part" class="progress-bar bg-info progress-bar-striped progress-bar-animated active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
            </div>
            <br />
            <div class="container">
                <div class="row">
                    @Translation.Translate("file"):&nbsp;
                    [<div id="prog-kind"></div>]&nbsp;
                    <div id="prog-name"></div>&emsp;
                    <div id="prog-pgfc"></div>/
                    <div id="prog-ttfc"></div>
                </div>
            </div>
        </div>
    </div>
    <br />
</div>

@if (HttpContext.Session.Get<bool>("DLQueryProgress") || HttpContext.Session.Get<bool>("LQueryProgress"))
{
    <script>
        $("#prog").show();
        @if (HttpContext.Session.Get<bool>("LQueryProgress"))
        {
            @:Launcher_Launch();
        }
        else
        {
            @:Launcher_Download();
        }
    </script>
}

@if (!HttpContext.Session.Get<bool>("DLQueryProgress") && !HttpContext.Session.Get<bool>("LQueryProgress"))
{
    <form id="form-login" method="post">
        <div class="form-group">
            <label for="memory">@Translation.Translate("launcher-memory")</label>
            <input type="number" class="form-control" value="@(Request.Cookies["Memory"] != null ? Request.Cookies["Memory"] : "1024")" id="memory" asp-for="Memory">
        </div>
        <div class="form-group">
            <label for="username">@Translation.Translate("launcher-username")</label>
            <input type="text" class="form-control" value="@Request.Cookies["Username"]" id="username" asp-for="Username">
        </div>
        <div class="form-group">
            <label for="password">@Translation.Translate("launcher-password")</label>
            <input type="password" class="form-control" value="@Request.Cookies["Password"]" id="password" asp-for="Password">
        </div>
        <div class="form-group">
            <label for="version">@Translation.Translate("launcher-version")</label>
            <select class="form-control" id="version" for="version" asp-for="Version">
                @foreach (var ver in LauncherModel.LoadVersions())
                {
                    <option value="@ver.Name">@ver.Name</option>
                }
            </select>
            <script>
                document.querySelector('#version').value = "@(Request.Cookies["Version"] != null ? Request.Cookies["Version"] : "1.16.5")";
            </script>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="fullscreen" asp-for="Fullscreen">
            <label class="form-check-label" for="fullscreen">@Translation.Translate("launcher-fullscreen")</label>
            <script>
                document.querySelector('#fullscreen').checked = @(Request.Cookies["Fullscreen"] == "True" ? "true" : "false");
            </script>
        </div>
        <br />
        <button type="submit" class="btn btn-primary" asp-page-handler="login" onclick="$('#form-login').hide();$('#prog').show();Launcher_Launch();">@Translation.Translate("launcher-login")</button>
        &emsp;
        <button type="submit" class="btn btn-primary" asp-page-handler="register">@Translation.Translate("launcher-register")</button>
        &emsp;
        <button type="submit" class="btn btn-primary" asp-page-handler="download" onclick="$('#form-login').hide();$('#prog').show();Launcher_Download();">@Translation.Translate("launcher-download")</button>
    </form>
}